name: edge_glm
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - ipython
  - jupyter
  - scipy
  - scikit-learn
  - nibabel
  - nilearn==0.9
  - matplotlib
  - seaborn
  - pip
  - pip:
    - yellowbrick

